name: NPM Publish
on:
    push:
        branches:
            - main
        paths:
            - src/**
    workflow_dispatch:
        inputs:
            versionIncrement:
                description: Version Increment
                required: true
                default: minor
                type: choice
                options:
                    - patch
jobs:
    npm-publish:
        runs-on: ubuntu-latest
        concurrency: repository
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.GH_TOKEN }}
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
                  registry-url: https://registry.npmjs.org/
                  cache: 'npm'
            - name: npm version patch
              run: |
                  TAG=$(npm version patch --no-git-tag-version)
                  echo "TAG=$(echo $TAG)" >> $GITHUB_ENV
            - run: npm ci
            - run: npm run build
            - uses: EndBug/add-and-commit@v7
              with:
                  default_author: github_actions
                  message: Release ${{ env.TAG }} [skip ci]
                  tag: ${{ env.TAG }}
            - run: npm publish --tag ${GITHUB_REF##*/}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}